# Build
# -------------------------------------

language: node_js
node_js:
    - "6"

# Deployment
# -------------------------------------

deploy:
    provider: npm
    on:
        tags: true
        node: "6"
    api_key:
        secure: "Z2z+gAfU7a4IS+GxkShdjkIGZA6Xs+BUaub+hRCxSQ4njWCE4/fmc7Qc6fJLO19KAslMZ7Dijzv7shkdJeshLkuqflRUwn3hN25uPKdgG8cI308a5RKGVHsXCmufEYbreHkKyuMo5L+K5jf+wJVU9rUKi3Qc9YJl1yC9HLpzzdV0GfdVdlDHvC578sRGsDFjRWTrMoz4bI54rCCChHr02v2io2yODKHW0Aaq9EGLTAX0yTF82YBB2dht59x2kLIGheewxfIQ2Q419isO5fcjBODuWKcEXyw84vJQ+nlsuUrXmp3ecgbJXaJUJN8ob34x4s0Ti3SI+ljL2Ue2+CPHUNkzqtO1JCZLa9Dkw0Ha9wukLTm0HqHDm0oAcZmAO3VarOG0hYIqxsGcOZyf/ClKMRmYYs0/Pz20xcGn/uij+ueLutkeIlrmqNMx8ubyHMpEM0XcUZush0vexVJXuPZAm7e5scAM65Ox6itNOaXYqJqcA/KJv2XOjP70vPj3914nDaGpzimupkUxB+ub79+Js+2CAnokuUTSriOwUJ8DfM0ogDiAwqxPXcZpQbuwh8NCBjTacIp7EJJWIjlLcj8dHHuJZFAMckjh43X8Si9XES1t5KEhe4dQUjuVj4JiRRWzI3eZ/Godg6LFsIQDb3iDKlaFA2HK12q3T2iu3M288AE="
    email: "lsphillips.mail@gmail.com"
